# Generated by Django 5.2.4 on 2026-02-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSiteRepairBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('problem_details', models.TextField()),
                ('parts_required', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'On-Site Repair Booking',
                'verbose_name_plural': 'On-Site Repair Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
