# Generated by Django 5.1.6 on 2025-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Throttle', 'Throttle'), ('Controller', 'Controller'), ('Bearing', 'Bearing'), ('Brake Shoe', 'Brake Shoe'), ('Charging Socket', 'Charging Socket'), ('Converter', 'Converter'), ('Disc Pad', 'Disc Pad'), ('Sensor', 'Sensor'), ('Junction Box', 'Junction Box'), ('Horn', 'Horn'), ('Mirror', 'Mirror'), ('Footrest', 'Footrest'), ('LED Light', 'LED Light'), ('Brake Lever', 'Brake Lever'), ('Speedometer', 'Speedometer'), ('Spring', 'Spring'), ('Lock Set', 'Lock Set'), ('Cables', 'Cables'), ('Wiring', 'Wiring'), ('MCB', 'MCB'), ('Ignition Lock', 'Ignition Lock'), ('Headlight', 'Headlight'), ('Taillight', 'Taillight'), ('Indicator', 'Indicator'), ('Display', 'Display'), ('Motor', 'Motor'), ('Seat', 'Seat'), ('Mudguard', 'Mudguard'), ('Body Cover', 'Body Cover'), ('Backrest', 'Backrest'), ('Toolkit', 'Toolkit'), ('Visor', 'Visor'), ('Switch', 'Switch'), ('Flasher', 'Flasher'), ('Charger', 'Charger'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
