# Generated by Django 5.1.6 on 2025-07-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_is_out_of_stock_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_types',
            field=models.ManyToManyField(blank=True, null=True, to='core.vehicletype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
