# Generated by Django 5.1.6 on 2025-07-17 05:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_compatible_vehicle_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bulk_discount_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bulk_discount_100',
        ),
        migrations.CreateModel(
            name='BulkDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('discount_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='core.product')),
            ],
            options={
                'ordering': ['-min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
