# Generated by Django 5.1.6 on 2025-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_types',
            field=models.ManyToManyField(blank=True, to='core.vehicletype'),
        ),
    ]
