# Generated by Django 5.1.6 on 2025-07-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deliveryaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype')),
            ],
            options={
                'unique_together': {('name', 'brand', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='name',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_types',
            field=models.ManyToManyField(blank=True, to='core.vehicletype'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_vehicle_models',
            field=models.ManyToManyField(blank=True, to='core.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiclemodel'),
        ),
    ]
