# Generated by Django 5.2.4 on 2025-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_grievanceofficer_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
