# Generated by Django 5.1.6 on 2025-08-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_compatible_vehicle_types'),
        ('core', '0014_alter_bulkdiscounttier_options_and_more'),
    ]

    operations = [
    ]
