# Generated by Django 5.1.6 on 2025-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20250813_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_models',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='core.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='core.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Scooter', 'Scooter'), ('Cycle', 'Cycle'), ('E-Rikshaw', 'E-Rikshaw')], max_length=20),
        ),
    ]
