# Generated by Django 5.1.6 on 2025-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_compatible_vehicle_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_models',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.vehicletype'),
        ),
    ]
