# Generated by Django 5.2.4 on 2025-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subheading', max_length=300, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('background_color', models.CharField(default='bg-gradient-to-r from-blue-600 to-indigo-700', max_length=50)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Slide order (0 = first)')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
