# Generated by Django 5.2.4 on 2025-08-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_heroslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
