# Generated by Django 5.2.4 on 2025-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_product_delivery_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EvWorx Logo', max_length=100)),
                ('logo_image', models.ImageField(help_text='Upload the website logo image.', upload_to='logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one logo should be active at a time.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website Logo',
                'verbose_name_plural': 'Website Logos',
            },
        ),
    ]
