# Generated by Django 5.2.4 on 2025-09-22 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_websitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage (default 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN Code for GST', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=5, help_text='Minimum Order Quantity (default = 5). Can be adjusted per product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of product in KG or relevant unit', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MOQRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.PositiveIntegerField(default=5, help_text='Required quantity of primary product')),
                ('allowed_quantity', models.PositiveIntegerField(default=1, help_text='How many dependent products allowed')),
                ('dependent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_moq_rules', to='core.product')),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_moq_rules', to='core.product')),
            ],
            options={
                'verbose_name': 'MOQ Rule',
                'verbose_name_plural': 'MOQ Rules',
                'unique_together': {('primary_product', 'dependent_product')},
            },
        ),
    ]
